version: '3'
services:
#mssql docker
  ebus-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    networks:
      - ebusnet

  ebus-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:eBus=Server=ebus-sql,1433;Database=170048;User=sa;Password=QWElkj132!;ConnectRetryCount=0
    ports:
      - 5000:5050
    networks:
      - ebusnet
    links:
      - ebus-sql
    depends_on:
      - ebus-sql
      
networks:
  ebusnet:
    driver: bridge      